<a href="https://colab.research.google.com/github/sudarsana-reddy/ml-practice-repo/blob/main/ca_ml_pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [24]:
x = torch.rand(5)
print(x)
x.requires_grad

tensor([0.5275, 0.6007, 0.1564, 0.6431, 0.3104])


False

In [3]:
loss = x**2 - 5

In [4]:
loss

tensor([-4.7170, -4.9987, -4.6275, -4.9532, -4.7963])

In [5]:
x.requires_grad_(True)

tensor([0.5320, 0.0357, 0.6104, 0.2164, 0.4514], requires_grad=True)

In [6]:
x

tensor([0.5320, 0.0357, 0.6104, 0.2164, 0.4514], requires_grad=True)

In [7]:
loss = x ** 2 -5

In [8]:
loss

tensor([-4.7170, -4.9987, -4.6275, -4.9532, -4.7963], grad_fn=<SubBackward0>)

In [9]:
loss.grad_fn

In [10]:
loss.backward(gradient=torch.ones(5))

In [11]:
x.grad

tensor([1.0640, 0.0714, 1.2207, 0.4329, 0.9027])

$$\frac{\partial y}{\partial x} =2x$$

In [12]:
2*x

tensor([1.0640, 0.0714, 1.2207, 0.4329, 0.9027], grad_fn=<MulBackward0>)

In [15]:
a = torch.rand(2,2, requires_grad=True)
a.requires_grad



True

In [16]:
b = a.detach()
b.requires_grad

False

In [17]:
c = torch.rand(2,2, requires_grad=True)



In [18]:
with torch.no_grad():
    c = a*2
    print(c.requires_grad)

False


In [19]:
y = a ** 2

In [20]:
y

tensor([[0.5977, 0.1108],
        [0.8814, 0.5069]], grad_fn=<PowBackward0>)

In [22]:
y.backward(torch.ones(2,2))

In [23]:
print(x.grad)

tensor([1.0640, 0.0714, 1.2207, 0.4329, 0.9027])
