<a href="https://colab.research.google.com/github/sudarsana-reddy/ml-practice-repo/blob/main/ca_ml_pytorch_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    """
    Returns the ltotal number of samples in the dataset
    """
    return len(self.X)

  def __getitem__(self, idx):
    """
    Returns the idx-th sample in the dataset
    """
    return self.X[idx], self.y[idx]


In [3]:
from sklearn.datasets import make_classification


In [5]:
data, target = make_classification(n_samples=1000, n_features=5)

In [6]:
custom_dataset = CustomDataset(X=data, y=target)


In [7]:
len(custom_dataset)

1000

In [12]:
custom_dataset[1][0].shape

(5,)

In [9]:
data.shape

(1000, 5)

In [11]:
import pandas as pd
pd.DataFrame(data).head()

0         1         2         3         4
0  0.190896 -2.365183 -0.531388  0.319223  1.780623
1  1.184789 -1.029982  0.059189  1.041762  0.757610
2  1.246376 -2.176563 -0.455993  0.396338  1.636598
3  0.281968  0.918286  0.817693  1.775338 -0.728800
4 -0.648458  1.057069 -0.195935 -1.489131 -0.769249

In [14]:
from sklearn.datasets import make_multilabel_classification

In [15]:
data, target = make_multilabel_classification(n_samples=1000, n_features=5, n_classes=3)

In [16]:
custom_dataset_mlb = CustomDataset(X=data, y=target)

In [17]:
custom_dataset_mlb[0]

(array([14., 27.,  5., 14.,  8.]), array([0, 1, 1]))

In [18]:
custom_dataset_mlb[1]

(array([ 9., 14.,  8., 16., 12.]), array([0, 1, 1]))

In [19]:
custom_dataset_mlb[5]

(array([11.,  7.,  2.,  9.,  6.]), array([0, 0, 1]))

In [22]:
from torch.utils.data import DataLoader
data_loader = DataLoader(custom_dataset, batch_size=8, shuffle=True)

In [21]:
custom_dataset[0]

(array([ 0.19089561, -2.36518292, -0.53138843,  0.31922295,  1.78062331]), 0)

In [23]:
data_iter = iter(data_loader)

In [24]:
data_iter

In [26]:
data_02 = data_iter.__next__()
features_02, target_02 = data_02

In [27]:
features_02

tensor([[-0.0784, -0.0829, -0.2938, -0.8435,  0.0793],
        [ 0.5125,  0.7994,  0.6134,  1.2398, -0.6284],
        [-0.2971, -0.8107, -0.6489, -1.3405,  0.6389],
        [-1.1795,  0.0122, -0.3185, -0.9996,  0.0105],
        [-0.0426,  0.7637, -0.1363, -1.0595, -0.5561],
        [ 0.8066,  3.0495,  1.2445,  1.3261, -2.3301],
        [-0.8275,  1.4499,  0.2476, -0.4384, -1.0868],
        [-0.8830, -1.3447,  0.3524,  2.2146,  0.9723]], dtype=torch.float64)

In [28]:
target_02

tensor([0, 1, 0, 0, 0, 1, 0, 1])