<a href="https://colab.research.google.com/github/sudarsana-reddy/ml-practice-repo/blob/main/ca_ml_pytorch_basics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch

In [19]:
import numpy as np

In [20]:
numpy_data = np.random.rand(2,3)

In [21]:
numpy_data

array([[0.07893975, 0.65584193, 0.54156162],
       [0.40389069, 0.05827555, 0.6235702 ]])

In [22]:
type(numpy_data)

numpy.ndarray

In [23]:
torch_numpy_data = torch.from_numpy(numpy_data)

In [24]:
torch_numpy_data

tensor([[0.0789, 0.6558, 0.5416],
        [0.4039, 0.0583, 0.6236]], dtype=torch.float64)

In [25]:
tensor_numpy_data = torch.tensor(numpy_data)

In [26]:
tensor_numpy_data

tensor([[0.0789, 0.6558, 0.5416],
        [0.4039, 0.0583, 0.6236]], dtype=torch.float64)

In [27]:
tensor_numpy_data.cpu().numpy()

array([[0.07893975, 0.65584193, 0.54156162],
       [0.40389069, 0.05827555, 0.6235702 ]])

#** Operations between Tensors**


In [28]:
numpy_data = np.random.rand(2,3)
numpy_data

array([[0.75311344, 0.65949148, 0.77228841],
       [0.0855717 , 0.73989884, 0.07100084]])

In [29]:
my_tns2 = torch.tensor(numpy_data)
my_tns2

tensor([[0.7531, 0.6595, 0.7723],
        [0.0856, 0.7399, 0.0710]], dtype=torch.float64)

In [30]:
my_tns1 = torch_numpy_data
my_tns1

tensor([[0.0789, 0.6558, 0.5416],
        [0.4039, 0.0583, 0.6236]], dtype=torch.float64)

In [32]:
torch.concat([my_tns1,my_tns2], dim=1)

tensor([[0.0789, 0.6558, 0.5416, 0.7531, 0.6595, 0.7723],
        [0.4039, 0.0583, 0.6236, 0.0856, 0.7399, 0.0710]], dtype=torch.float64)

In [34]:
my_tns1.clip(0.2, 0.8)

tensor([[0.2000, 0.6558, 0.5416],
        [0.4039, 0.2000, 0.6236]], dtype=torch.float64)

In [35]:
my_tns1.mul(my_tns2)

tensor([[0.0595, 0.4325, 0.4182],
        [0.0346, 0.0431, 0.0443]], dtype=torch.float64)

In [36]:
my_tns1 * my_tns2

tensor([[0.0595, 0.4325, 0.4182],
        [0.0346, 0.0431, 0.0443]], dtype=torch.float64)

In [42]:
my_tns1.matmul(my_tns2.T)

tensor([[0.9102, 0.5305],
        [0.8242, 0.1220]], dtype=torch.float64)

In [39]:
my_tns2.T

tensor([[0.7531, 0.0856],
        [0.6595, 0.7399],
        [0.7723, 0.0710]], dtype=torch.float64)

In [43]:
my_sum = my_tns2.sum()

In [44]:
my_sum

tensor(3.0814, dtype=torch.float64)

In [45]:
my_sum.item()

3.081364711986411

In [46]:
type(my_sum.item())

float

In [61]:
matrix_a = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [62]:
matrix_a

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [67]:
matrix_b = matrix_a.clone()
matrix_b

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [68]:
matrix_b + matrix_a

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [69]:
matrix_b.mean()

tensor(9.5000)

In [72]:
matrix_b.mean(dim=0)

tensor([ 8.,  9., 10., 11.])

In [73]:
matrix_b.sum(dim=0)/matrix_b.shape[0]

tensor([ 8.,  9., 10., 11.])