<a href="https://colab.research.google.com/github/sudarsana-reddy/ml-practice-repo/blob/main/pytorch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_data =[[1,2],[3,4]]
my_tensor = torch.tensor(my_data)
print(my_tensor)

tensor([[1, 2],
        [3, 4]])


In [3]:
my_tensor.dtype

torch.int64

In [10]:
my_tensor.type()

'torch.LongTensor'

In [7]:
my_tensor.device

device(type='cpu')

In [14]:
my_tensor_gpu = my_tensor.to('cuda')

In [15]:
torch.cuda.current_device()

0

In [16]:
my_tensor_gpu.device

device(type='cuda', index=0)

In [21]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [22]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [23]:
new_tensor = torch.zeros(2,2)

In [24]:
new_tensor.dtype

torch.float32

In [25]:
new_tensor.type()

'torch.FloatTensor'

In [27]:
updated_tensor = new_tensor.new_tensor(my_data)

In [28]:
updated_tensor.dtype

torch.float32

In [31]:
another_tensor = torch.ones((2,2),dtype=torch.int8, device='cuda')

In [32]:
another_tensor

tensor([[1, 1],
        [1, 1]], device='cuda:0', dtype=torch.int8)

In [33]:
another_tensor.device

device(type='cuda', index=0)

In [35]:
new_data = [[1,2], [3,4], [5,6]]
new_data_updated = another_tensor.new_tensor(new_data)

In [36]:
new_data_updated

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0', dtype=torch.int8)

In [38]:
shape = (2,3,)
my_tensor_random = torch.rand(shape)

In [39]:
my_tensor_random

tensor([[0.7778, 0.6152, 0.6185],
        [0.3631, 0.7628, 0.1535]])

In [43]:
torch.rand_like(my_tensor_random, dtype=torch.float)

tensor([[0.1968, 0.7717, 0.2963],
        [0.0511, 0.2818, 0.9392]])